### ISSUE TITLE
How to fix my error

### ISSUE THREAD

**Issue by anhtester** [sskorol/test-data-supplier#111]
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.initializeForJava11(ClassLoaderWeavingAdaptor.java:1072)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.defineClass(ClassLoaderWeavingAdaptor.java:1099)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.access$300(ClassLoaderWeavingAdaptor.java:66)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor$SimpleGeneratedClassHandler.acceptClass(ClassLoaderWeavingAdaptor.java:150)
	at org.aspectj.weaver.tools.WeavingAdaptor$WeavingClassFileProvider$1.acceptResult(WeavingAdaptor.java:920)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1434)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1195)
	at org.aspectj.weaver.tools.WeavingAdaptor.getWovenBytes(WeavingAdaptor.java:551)
	at org.aspectj.weaver.tools.WeavingAdaptor.weaveClass(WeavingAdaptor.java:387)
	at org.aspectj.weaver.loadtime.Aj.preProcess(Aj.java:116)
	at org.aspectj.weaver.loadtime.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:51)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1217)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:1010)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:944)
	at org.testng.TestNG.initializeEverything(TestNG.java:1041)
	at org.testng.TestNG.run(TestNG.java:1052)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang to unnamed module @9225652
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259)
	... 40 more
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.bindTo_Method" is null
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.defineClass(ClassLoaderWeavingAdaptor.java:1102)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.access$300(ClassLoaderWeavingAdaptor.java:66)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor$SimpleGeneratedClassHandler.acceptClass(ClassLoaderWeavingAdaptor.java:150)
	at org.aspectj.weaver.tools.WeavingAdaptor$WeavingClassFileProvider$1.acceptResult(WeavingAdaptor.java:920)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1434)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1195)
	at org.aspectj.weaver.tools.WeavingAdaptor.getWovenBytes(WeavingAdaptor.java:551)
	at org.aspectj.weaver.tools.WeavingAdaptor.weaveClass(WeavingAdaptor.java:387)
	at org.aspectj.weaver.loadtime.Aj.preProcess(Aj.java:116)
	at org.aspectj.weaver.loadtime.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:51)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1217)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:1010)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:944)
	at org.testng.TestNG.initializeEverything(TestNG.java:1041)
	at org.testng.TestNG.run(TestNG.java:1052)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
java.util.ServiceConfigurationError: org.testng.ITestNGListener: io.github.sskorol.core.DataProviderTransformer Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:1010)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:944)
	at org.testng.TestNG.initializeEverything(TestNG.java:1041)
	at org.testng.TestNG.run(TestNG.java:1052)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.NoClassDefFoundError: io/github/sskorol/core/DataProviderTransformer$AjcClosure1
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
	... 10 more
Caused by: java.lang.ClassNotFoundException: io.github.sskorol.core.DataProviderTransformer$AjcClosure1
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 18 more

Process finished with exit code -1

![image](https://user-images.githubusercontent.com/87883620/161421482-fdf6f922-c74d-41d0-8e1d-3ad41ccfde71.png)

![image](https://user-images.githubusercontent.com/87883620/161421497-5a710409-2410-421d-b72b-626df058439e.png)

**Comment by anhtester** [comment]
I using JDK 17.0.2

**Comment by anhtester** [comment]
![image](https://user-images.githubusercontent.com/87883620/161423394-80d0926d-9ae3-4a2c-bf84-203167dbefd0.png)

**Comment by sskorol** [comment]
@anhtester share your pom.xml, please.

**Comment by anhtester** [comment]
> @anhtester share your pom.xml, please.

https://github.com/anhtester/AutomationFrameworkSelenium/blob/main/pom.xml

**Comment by anhtester** [comment]
And why can't I use DataProvider and DataSupplier in parallel in my project?

![image](https://user-images.githubusercontent.com/87883620/161516600-809002e9-ce29-49f5-83b5-32d85daa4b4d.png)

**Comment by anhtester** [comment]
I can not read this Excel file with sheet "SignIn" and "Client"
You can check it. Thank you so much.

[ClientsDataExcel.xlsx](https://github.com/sskorol/test-data-supplier/files/8408921/ClientsDataExcel.xlsx)

![image](https://user-images.githubusercontent.com/87883620/161527184-5b72e464-6b8d-461d-a5f2-2b88705efe02.png)

**Comment by sskorol** [comment]
Please don't create a mess of questions a single issue. Split them.

As far as I can see from your pom.xml, you compile your project with java 8: https://github.com/anhtester/AutomationFrameworkSelenium/blob/main/pom.xml#L14. So it means you can't use the latest data-supplier with it as the recent version is compiled with java 11. So you should either upgrade your project to java 11+, or switch to test-data-supplier 1.7.0. But note that those old versions are not maintained anymore and there's no excel support as well.

You can use both old and new data providers. But if you want to get IDE hints and navigation, you should choose only one in settings (see plugin's README) as 2 plugins are conflicting.

**Comment by anhtester** [comment]
Yeah ok thank you. I shall update pom.xml and feedback for you.

**Comment by anhtester** [comment]
It is having problems reading the excel file. Please check Issue 112
[](https://github.com/sskorol/test-data-supplier/issues/112)

**Comment by anhtester** [comment]
It is an error with OPEN JDK 17.0.2.
Forced me to run with Open JDK 15.0.2

![image](https://user-images.githubusercontent.com/87883620/161610305-10d238d3-3891-44b6-9428-98e0afe80b05.png)

**Comment by sskorol** [comment]
Well, you should realize that it's usually not enough to update a single library when you migrate from java 8 to java 17. There were a bunch of changes made in lots of other libraries to support such migration. So make sure all the dependencies in your projects support java 17.

**Comment by anhtester** [comment]
Why are you don't using the data-supplier library for JDK 8 and supporting it to read Excel ??

**Comment by sskorol** [comment]
Because jdk 8 is 8 years old. Most of the libraries that are used as dependencies have already been upgraded to newer versions (at least jdk 11). So keeping jdk 8 support means balancing between new and old libraries' versions, resolving conflicts, inability to use new java features, etc. But the effort I'll invest maintaining 2 versions is much higher than a simple migration of a single project from java 8 to java 11.

**Comment by anhtester** [comment]
Thank you so much. I will close this issue.
