### ISSUE TITLE
Unable to read the XLSX data getting exception to check provided path and converter unable to cast

### ISSUE THREAD

**Issue by abidkhan4357** [sskorol/test-data-supplier#114]
Unable to read the xlsx data exception showing to check provided path even though @Source is provided in pojo class
Also .withSource() also used in runner class. If I removed the @Source from pojo still I have getting error and vise versa if I remove the .withSource() I still get exception to check the path. My xlsx is located in test/resources file path. 

Steps to Reproduce:
1. Create Pojo class

`
import com.creditdatamw.zerocell.annotation.Column;
import io.github.sskorol.data.Sheet;
import io.github.sskorol.data.Source;
import lombok.Getter;
import org.tutorialsninja.converters.StringToBrowserTypeConverter;

@Getter
@Source(path = "testdata.xlsx")
@Sheet(name = "RunManager")
public class ExcelData {

    @Column(name = "run", index = 0)
    private String run;

    @Column(name = "tc", index = 1)
    private String testcase;

    @Column(name = "browser", index = 2, converterClass = StringToBrowserTypeConverter.class)
    private String browser;

}

Convert class:
import org.aeonbits.owner.Converter;
import org.tutorialsninja.enums.BrowserType;

import java.lang.reflect.Method;
import java.util.Map;

public class StringToBrowserTypeConverter implements Converter<BrowserType> {

    @Override
    public BrowserType convert(Method method, String browserName) {

        Map<String, BrowserType> stringBrowserTypeMap = Map.of("CHROME", BrowserType.CHROME,
                "FIREFOX", BrowserType.FIREFOX);
        return stringBrowserTypeMap.getOrDefault(browserName.toUpperCase(), BrowserType.CHROME);
    }
}

2. Create Runner class

import io.github.sskorol.core.DataSupplier;
import io.github.sskorol.data.XlsxReader;
import one.util.streamex.StreamEx;
import org.testng.annotations.Test;
import org.tutorialsninja.exceldata.ExcelData;

import java.lang.reflect.Method;

import static io.github.sskorol.data.TestDataReader.use;

public class TestDataSuppRunner {

    @Test(dataProvider = "getDataFromExcel")
    public void testcase1(ExcelData data) {
        System.out.println(data.getBrowser());
    }

    @DataSupplier
    public StreamEx<ExcelData> getDataFromExcel(Method method) {
        return use(XlsxReader.class)
                .withTarget(ExcelData.class)
                .withSource("testdata.xlsx")
                .read()
                .filter(excelData -> excelData.getTestcase().equalsIgnoreCase(method.getName()));
    }
}
[](url)

`

Java Version: 11.0.13 2021-10-19 LTS
Java Compiler version: 11

. Note: for support questions, please use Stackoverflow. 
. This repository is for feature requests and bug reports only.
.
. Make sure you have a clear name for your issue. An example of good issue names:
.
. - NPE occurs while using DS with class level Test annotation
. - Add an ability to use DS with Factory annotation
. - External data sources support
)

### I'm submitting 
 - [- ] bug report
 - [ ] feature request
 
### Environment

| Test Data Supplier | 1.9.7 |
| --- | --- |
| TestNG | 7.4.0 |
| Build tool | Maven 3.8.1|
| IDE | IntelliJ@2022.1 |

### Is the issue reproducible on a runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ -] IntelliJ
- [ ] NetBeans

### What is the expected behavior?
[//]: # (
This should read the data from xlsx file
)

### What is the actual behavior?
[//]: # (
Unable to read data and throws following exception
1. Caused by: java.lang.IllegalArgumentException: Unable to read XLSX data to class org.tutorialsninja.exceldata.ExcelData. Check provided path.

2. Caused by: java.lang.ClassCastException: class org.tutorialsninja.converters.StringToBrowserTypeConverter cannot be cast to class com.creditdatamw.zerocell.converter.Converter (org.tutorialsninja.converters.StringToBrowserTypeConverter and com.creditdatamw.zerocell.converter.Converter are in unnamed module of loader &apos;app&apos;)
)

**Stack Trace:**
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[Utils] [ERROR] [Error] org.joor.ReflectException: java.lang.reflect.InvocationTargetException
	at org.joor.Reflect.on(Reflect.java:914)
	at org.joor.Reflect.call(Reflect.java:575)
	at io.github.sskorol.utils.ReflectionUtils.invokeDataSupplier(ReflectionUtils.java:69)
	at io.github.sskorol.model.DataSupplierMetaData.obtainReturnValue(DataSupplierMetaData.java:54)
	at io.github.sskorol.model.DataSupplierMetaData.transform(DataSupplierMetaData.java:40)
	at io.github.sskorol.model.DataSupplierMetaData.&lt;init&gt;(DataSupplierMetaData.java:36)
	at io.github.sskorol.core.DataProviderTransformer.getMetaData(DataProviderTransformer.java:43)
	at io.github.sskorol.core.DataProviderTransformer.supplySeqData(DataProviderTransformer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.joor.Reflect.on(Reflect.java:910)
	... 38 more
Caused by: org.joor.ReflectException: java.lang.reflect.InvocationTargetException
	at org.joor.Reflect.on(Reflect.java:914)
	at org.joor.Reflect.call(Reflect.java:575)
	at org.joor.Reflect.call(Reflect.java:528)
	at io.github.sskorol.data.TestDataReader$DataBuilder.read(TestDataReader.java:54)
	at org.tutorialsninja.tests.TestDataSuppRunner.getDataFromExcel(TestDataSuppRunner.java:25)
	... 43 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.joor.Reflect.on(Reflect.java:910)
	... 47 more
Caused by: java.lang.IllegalArgumentException: Unable to read XLSX data to class org.tutorialsninja.exceldata.ExcelData. Check provided path.
	at io.github.sskorol.data.XlsxReader.read(XlsxReader.java:37)
	... 52 more
Caused by: java.lang.ClassCastException: class org.tutorialsninja.converters.StringToBrowserTypeConverter cannot be cast to class com.creditdatamw.zerocell.converter.Converter (org.tutorialsninja.converters.StringToBrowserTypeConverter and com.creditdatamw.zerocell.converter.Converter are in unnamed module of loader &apos;app&apos;)
	at com.creditdatamw.zerocell.handler.EntityExcelSheetHandler.cacheConverters(EntityExcelSheetHandler.java:52)
	at com.creditdatamw.zerocell.handler.EntityExcelSheetHandler.&lt;init&gt;(EntityExcelSheetHandler.java:42)
	at com.creditdatamw.zerocell.handler.EntityHandler.createSheetHandler(EntityHandler.java:116)
	at com.creditdatamw.zerocell.handler.EntityHandler.&lt;init&gt;(EntityHandler.java:49)
	at com.creditdatamw.zerocell.Reader$ReaderBuilder.list(Reader.java:112)
	at io.github.sskorol.data.XlsxReader.read(XlsxReader.java:34)
	... 52 more

Test ignored.

===============================================
Default Suite
Total tests run: 1, Passes: 0, Failures: 0, Skips: 1
===============================================

Process finished with exit code 0

**Comment by sskorol** [comment]
Please reformat your code and logs using markdown syntax.

**Comment by sskorol** [comment]
On the other hand, the message is pretty straightforward:
```shell
Caused by: java.lang.ClassCastException: class org.tutorialsninja.converters.StringToBrowserTypeConverter cannot be cast to class com.creditdatamw.zerocell.converter.Converter
```

As far as I can see from your code, you are using the wrong import:

```java
import org.aeonbits.owner.Converter;

public class StringToBrowserTypeConverter implements Converter {
```

`org.aeonbits.owner.Converter` != `com.creditdatamw.zerocell.converter.Converter`.
