### ISSUE TITLE
Getting reflection error while reading the xlsx file

### ISSUE THREAD

**Issue by abidkhan4357** [sskorol/test-data-supplier#117]
### Environment

| Test Data Supplier | 1.9.7 |
| --- | --- |
| TestNG | 7.4.0 |
| Build tool | Maven 3.8.1 |
| IDE | IntelliJ@2022.1 |
| Java | 11.0.13 |

### Is the issue reproducible on a runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [- ] IntelliJ
- [ ] NetBeans
```


`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
[Utils] [ERROR] [Error] org.joor.ReflectException: java.lang.reflect.InvocationTargetException
	at org.joor.Reflect.on(Reflect.java:914)
	at org.joor.Reflect.call(Reflect.java:575)
	at io.github.sskorol.utils.ReflectionUtils.invokeDataSupplier(ReflectionUtils.java:69)
	at io.github.sskorol.model.DataSupplierMetaData.obtainReturnValue(DataSupplierMetaData.java:54)
	at io.github.sskorol.model.DataSupplierMetaData.transform(DataSupplierMetaData.java:40)
	at io.github.sskorol.model.DataSupplierMetaData.&lt;init&gt;(DataSupplierMetaData.java:36)
	at io.github.sskorol.core.DataProviderTransformer.getMetaData(DataProviderTransformer.java:43)
	at io.github.sskorol.core.DataProviderTransformer.supplySeqData(DataProviderTransformer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.joor.Reflect.on(Reflect.java:910)
	... 38 more
Caused by: org.joor.ReflectException: java.lang.reflect.InvocationTargetException
	at org.joor.Reflect.on(Reflect.java:914)
	at org.joor.Reflect.call(Reflect.java:575)
	at org.joor.Reflect.call(Reflect.java:528)
	at io.github.sskorol.data.TestDataReader$DataBuilder.read(TestDataReader.java:54)
	at org.tutorialsninja.tests.TestDataSuppRunner.getDataFromExcel(TestDataSuppRunner.java:25)
	... 43 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.joor.Reflect.on(Reflect.java:910)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/output/UnsynchronizedByteArrayOutputStream
	at org.apache.poi.poifs.filesystem.FileMagic.valueOf(FileMagic.java:209)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.verifyZipHeader(ZipHelper.java:143)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipFile(ZipHelper.java:201)
	at org.apache.poi.openxml4j.opc.ZipPackage.&lt;init&gt;(ZipPackage.java:166)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:282)
	at com.creditdatamw.zerocell.ReaderUtil.process(ReaderUtil.java:60)
	at com.creditdatamw.zerocell.handler.EntityHandler.process(EntityHandler.java:130)
	at com.creditdatamw.zerocell.Reader$ReaderBuilder.list(Reader.java:119)
	at io.github.sskorol.data.XlsxReader.read(XlsxReader.java:34)
	... 52 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 61 more`
```

```
Test ignored.

===============================================
Default Suite
Total tests run: 1, Passes: 0, Failures: 0, Skips: 1
===============================================


Process finished with exit code
``` 0


Pom.xml

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.tutorialsninja</groupId>
    <artifactId>TutorialsNinjaWebAutomationFramework</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <java-compiler.version>11</java-compiler.version>
        <maven.compiler.target>11</maven.compiler.target>
        <owner.version>1.0.12</owner.version>
        <extentreport.version>5.0.8</extentreport.version>
        <assertjcore.version>3.21.0</assertjcore.version>
        <testng.version>7.4.0</testng.version>
        <webdrivermanager.version>5.0.3</webdrivermanager.version>
        <selenium.version>4.1.1</selenium.version>
        <lombok.version>1.18.20</lombok.version>
        <javafaker.version>1.0.2</javafaker.version>
        <awaitility.version>4.1.1</awaitility.version>
        <noexception.version>1.7.1</noexception.version>
        <guice.verion>5.1.0</guice.verion>
        <datasupplier.version>1.9.7</datasupplier.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>com.machinezoo.noexception</groupId>
            <artifactId>noexception</artifactId>
            <version>${noexception.version}</version>
        </dependency>

        <dependency>
            <groupId>org.aeonbits.owner</groupId>
            <artifactId>owner</artifactId>
            <version>${owner.version}</version>
        </dependency>

        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <version>${awaitility.version}</version>
        </dependency>

        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>${extentreport.version}</version>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertjcore.version}</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>${webdrivermanager.version}</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>

        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>${javafaker.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.sskorol</groupId>
            <artifactId>test-data-supplier</artifactId>
            <version>${datasupplier.version}</version>
        </dependency>

    </dependencies>

</project>`



//Code for Pojo
`import com.creditdatamw.zerocell.annotation.Column;
import io.github.sskorol.data.Sheet;
import lombok.Getter;
import org.tutorialsninja.converters.StringToBrowserTypeConverterForExcel;
import org.tutorialsninja.enums.BrowserType;


@Getter
@Sheet(name = "RunManager")
public class ExcelData {

    @Column(name = "run", index = 0)
    private String run;

    @Column(name = "tc", index = 1)
    private String testcase;

    @Column(name = "browser", index = 2, converterClass = StringToBrowserTypeConverterForExcel.class)
    private BrowserType browser;

}
`



 //Code for Runner class
`package org.tutorialsninja.tests;

import io.github.sskorol.core.DataSupplier;
import io.github.sskorol.data.XlsxReader;
import one.util.streamex.StreamEx;
import org.testng.annotations.Test;
import org.tutorialsninja.exceldata.ExcelData;

import java.lang.reflect.Method;

import static io.github.sskorol.data.TestDataReader.use;

public class TestDataSuppRunner {

    @Test(dataProvider = "getDataFromExcel")
    public void testcase1(ExcelData data) {
        System.out.println(data);
    }

    @DataSupplier
    public StreamEx<ExcelData> getDataFromExcel(Method method) {
        return use(XlsxReader.class)
                .withTarget(ExcelData.class)
                .withSource("testdata.xlsx")
                .read()
                .filter(excelData -> excelData.getTestcase().equalsIgnoreCase(method.getName()));
    }
}
`

**Comment by sskorol** [comment]
@abidkhan4357 what about code that produces this exception?

**Comment by abidkhan4357** [comment]
@sskorol  updated with code snippet and here is the xls file                                                                                                                                                                                      
[testdata.xlsx](https://github.com/sskorol/test-data-supplier/files/8534268/testdata.xlsx)

**Comment by sskorol** [comment]
I don't see anything specific in your code that might produce this error, so I believe it's a dependency hell issue. Please follow the above instructions to find the conflict and resolve it by excluding corresponding dependency or adding required `commons` version to your pom.

**Comment by abidkhan4357** [comment]
@sskorol can you help with it. I have never dealt with such issue. I have downloaded a maven dependency analyzer. Please see added dependency conflicts

**Comment by abidkhan4357** [comment]
[](url)

**Comment by abidkhan4357** [comment]
@sskorol 
![Commons1](https://user-images.githubusercontent.com/49580193/165198067-07fd74dd-c365-422e-a6aa-f9e115d4531b.PNG)
![Commons2](http
![Capture3](https://user-images.githubusercontent.com/49580193/165198114-3d63d1fc-fd8c-43dc-b479-d8daf29695aa.PNG)
s://user-images.githubusercontent.com/49580193/165198079-74f6fa40-e0d9-4b7c-adc7-e3d1cfe94084.PNG)
`

**Comment by abidkhan4357** [comment]
Closing issue as your were right on the commons dependency issue.
