### ISSUE TITLE
[BUG] Issue occurs when try to run code on Jenkins to read data from excel 

### ISSUE THREAD

**Issue by gupta77** [sskorol/test-data-supplier#141]
[//]: # (
. Note: for support questions, please use Stackoverflow. 
. This repository is for feature requests and bug reports only.
.
. Make sure you have a clear name for your issue. An example of good issue names:
.
. - NPE occurs while using DS with class level Test annotation
. - Add an ability to use DS with Factory annotation
. - External data sources support
)

### Description
Maven - 3.8.4
Java - 8
Used Test Data Supplier dependency to read data from excel, working fine in windows 
getting exceptions when running the same code in Jenkins on a Linux environment.
FYI - I have checked the workspace and file is available on Jenkins workspace where its shows error 

### Issue Type 
 - [x] bug report
 - [ ] feature request
 
### Environment

| Component          | Version         |
|--------------------|-----------------|
| Test Data Supplier | 1.9.9         |
| TestNG             | 7.0.0           |
| Build tool         | maven 3.8.4    |
| IDE                | IntelliJ@2022.1 |

### Can be reproduced via

- [ ] Bash
- [x] Maven
- [ ] Gradle
- [ ] Eclipse
- [ ] IntelliJ

### Expected behavior
[//]: # (
. Describe your vision on this issue.
)
ToDo

### Actual behavior
[//]: # (
. If the current behavior is a bug, please provide the steps to reproduce an issue. And if possible, a minimal demo of the problem.
)
ToDo

### What's the motivation for changing the current behavior?
[//]: # (
. Clarify your use case.
)
ToDo

### Additional information 
[//]: # (
. 18:27:37.984 [TestNG-test=KYVOS API Automation-1] ERROR org.apache.poi.openxml4j.opc.ZipPackage - Error in zip file /data1/jenkins/workspace/New%20Kyvos%20API%20Sanity%20Suite/target/test-classes/excel/CubeCacheExcel.xlsx - falling back to stream processing (i.e. ignoring zip central directory)
[Utils] [ERROR] [Error] org.joor.ReflectException: java.lang.reflect.InvocationTargetException
	at org.joor.Reflect.on(Reflect.java:781)
	at org.joor.Reflect.call(Reflect.java:455)
	at io.github.sskorol.utils.ReflectionUtils.invokeDataSupplier(ReflectionUtils.java:72)
	at io.github.sskorol.model.DataSupplierMetaData.obtainReturnValue(DataSupplierMetaData.java:63)
	at io.github.sskorol.model.DataSupplierMetaData.transform(DataSupplierMetaData.java:49)
	at io.github.sskorol.model.DataSupplierMetaData.&lt;init&gt;(DataSupplierMetaData.java:37)
	at io.github.sskorol.core.DataProviderTransformer.getMetaData_aroundBody0(DataProviderTransformer.java:60)
	at io.github.sskorol.core.DataProviderTransformer$AjcClosure1.run(DataProviderTransformer.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:229)
	at io.github.sskorol.core.DataSupplierAspect.onDataPreparation(DataSupplierAspect.java:50)
	at io.github.sskorol.core.DataProviderTransformer.getMetaData(DataProviderTransformer.java:60)
	at io.github.sskorol.core.DataProviderTransformer.supplySeqData(DataProviderTransformer.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:820)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.joor.Reflect.on(Reflect.java:777)
	... 30 more
Caused by: org.joor.ReflectException: java.lang.reflect.InvocationTargetException
	at org.joor.Reflect.on(Reflect.java:781)
	at org.joor.Reflect.call(Reflect.java:455)
	at org.joor.Reflect.call(Reflect.java:408)
	at io.github.sskorol.data.TestDataReader$DataBuilder.read(TestDataReader.java:50)
	at com.kyvos.tests.cube.CubeCacheRuleTest.getCubeCacheData(CubeCacheRuleTest.java:26)
	... 35 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.joor.Reflect.on(Reflect.java:777)
	... 39 more
Caused by: java.lang.IllegalArgumentException: Unable to read XLSX data to class com.kyvos.utils.cubeccache.CubeCacheExcel. Check provided path.
	at com.kyvos.utils.XlsxReader.read(XlsxReader.java:39)
	... 44 more
Caused by: org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can&apos;t open the specified file input stream from file: &apos;/data1/jenkins/workspace/New%20Kyvos%20API%20Sanity%20Suite/target/test-classes/excel/CubeCacheExcel.xlsx&apos;
)
ToDo

**Comment by sskorol** [comment]
I'm not really sure I got this one:
```shell
ERROR org.apache.poi.openxml4j.opc.ZipPackage - Error in zip file /data1/jenkins/workspace/New%20Kyvos%20API%20Sanity%20Suite/target/test-classes/excel/CubeCacheExcel.xlsx - falling back to stream processing (i.e. ignoring zip central directory)
```
Are you trying to read an excel file from zip archive?

**Comment by gupta77** [comment]
- No, I am trying getting the updated code from git and then leveraging test data Supplier metiod to read data from Jenkins workspace 
- 
- Well, Issue got resolved If I removed all white space between job name so looks like there is some issue with job name have some white space between two words 

 - I can't update test-data-supplier and testng as I am using Java 8 and with higher version I ma getting some eroors while compiling the code

**Comment by sskorol** [comment]
@gupta77 good to know it's resolved. Can you share how do you set the path to the excel spreadsheet in code and where it's physically located in your project structure?
Note that, unfortunately, I don't have enough capacity to maintain old DS versions. Java moves forward with 6 months release cycles. So DS is always bound to the latest LTS version. And that's what I'm able to maintain.

**Comment by sskorol** [comment]
Feel free to reopen, if the issue is still in place.
