### ISSUE TITLE
[BUG] module java.base does not open java.lang to unnamed module @3d285129

### ISSUE THREAD

**Issue by AmitBhaawsar** [sskorol/test-data-supplier#153]
[//]: # (
. Note: for support questions, please use Stackoverflow. 
. This repository is for feature requests and bug reports only.
.
. Make sure you have a clear name for your issue. An example of good issue names:
.
. - NPE occurs while using DS with class level Test annotation
. - Add an ability to use DS with Factory annotation
. - External data sources support
)

### Description
[//]: # (
. Describe your problem in several sentences to give context.
ava.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.initializeForJava11(ClassLoaderWeavingAdaptor.java:1069)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.defineClass(ClassLoaderWeavingAdaptor.java:1096)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.access$300(ClassLoaderWeavingAdaptor.java:66)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor$SimpleGeneratedClassHandler.acceptClass(ClassLoaderWeavingAdaptor.java:150)
	at org.aspectj.weaver.tools.WeavingAdaptor$WeavingClassFileProvider$1.acceptResult(WeavingAdaptor.java:916)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1430)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1192)
	at org.aspectj.weaver.tools.WeavingAdaptor.getWovenBytes(WeavingAdaptor.java:549)
	at org.aspectj.weaver.tools.WeavingAdaptor.weaveClass(WeavingAdaptor.java:385)
	at org.aspectj.weaver.loadtime.Aj.preProcess(Aj.java:115)
	at org.aspectj.weaver.loadtime.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:51)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1217)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:1017)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:951)
	at org.testng.TestNG.initializeEverything(TestNG.java:1048)
	at org.testng.TestNG.run(TestNG.java:1059)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang to unnamed module @3d285129
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259)
	... 40 more
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.bindTo_Method" is null
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.defineClass(ClassLoaderWeavingAdaptor.java:1099)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.access$300(ClassLoaderWeavingAdaptor.java:66)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor$SimpleGeneratedClassHandler.acceptClass(ClassLoaderWeavingAdaptor.java:150)
	at org.aspectj.weaver.tools.WeavingAdaptor$WeavingClassFileProvider$1.acceptResult(WeavingAdaptor.java:916)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1430)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1192)
	at org.aspectj.weaver.tools.WeavingAdaptor.getWovenBytes(WeavingAdaptor.java:549)
	at org.aspectj.weaver.tools.WeavingAdaptor.weaveClass(WeavingAdaptor.java:385)
	at org.aspectj.weaver.loadtime.Aj.preProcess(Aj.java:115)
	at org.aspectj.weaver.loadtime.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:51)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1217)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:1017)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:951)
	at org.testng.TestNG.initializeEverything(TestNG.java:1048)
	at org.testng.TestNG.run(TestNG.java:1059)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
java.util.ServiceConfigurationError: org.testng.ITestNGListener: io.github.sskorol.core.DataProviderTransformer Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:1017)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:951)
	at org.testng.TestNG.initializeEverything(TestNG.java:1048)
	at org.testng.TestNG.run(TestNG.java:1059)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.NoClassDefFoundError: io/github/sskorol/core/DataProviderTransformer$AjcClosure1
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
	... 10 more
Caused by: java.lang.ClassNotFoundException: io.github.sskorol.core.DataProviderTransformer$AjcClosure1
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 18 more

Process finished with exit code -1
)
ToDo

### Issue Type 
 - [1 ] bug report
 - [ ] feature request
 
### Environment

| Component          | Version         |
|--------------------|-----------------|
| Test Data Supplier | 2.0.0           |
| TestNG             | 7.6.0           |
| Build tool         | gradle@7.4.2    |
| IDE                | IntelliJ@2022.1 |

### Can be reproduced via

- [ ] Bash
- [1 ] Maven
- [ ] Gradle
- [ ] Eclipse
- [ ] IntelliJ

### Expected behavior
[//]: # (
. Describe your vision on this issue.
)
ToDo

### Actual behavior
[//]: # (
. If the current behavior is a bug, please provide the steps to reproduce an issue. And if possible, a minimal demo of the problem.
)
ToDo

### What's the motivation for changing the current behavior?
[//]: # (
. Clarify your use case.
)
ToDo

### Additional information 
[//]: # (
. Detailed explanation, stacktrace, related issues, suggestions on 
. how to fix, links for us to understand a context, e.g. Stackoverflow
)
ToDo

**Comment by sskorol** [comment]
@sampathraghupatruni that's a different issue. Please create a new ticket and attach the code of how you create data supplier + provide some info on how you execute your test (mvn, IDE, etc).

**Comment by neehalchowdekar** [comment]
Facing the same issue when running through mvn clean test command and also from testng.xml file, but for fine if i clean the project and run separately the @Test method

**Comment by neehalchowdekar** [comment]
I did some iteration found out that the `mvn clean test` is throwing error, but if I run just `mvn test` it is working fine

**Comment by sskorol** [comment]
@neehalchowdekar can you provide a minimal project to reproduce the issue? As for me it sounds like a configuration problem. It's hard to debug without clear reproduction steps.

**Comment by VigneshGuhan** [comment]
@sampathraghupatruni @AmitBhaawsar @sskorol 

I was even facing the above issue.
If I place the target file in the "java" package , I was getting this error.

Once I moved the file to resource folder and passed the pathname directing from resource folder in the Source Parameter("TestDataSupplierFile.json") instead of path from the root directory, it worked as expected.

**Comment by sskorol** [comment]
@VigneshGuhan `resource`folder was designed exactly for the reason of getting a quick access to the non-code files like test data or configs. Everything you put to resources automatically appears in a classpath. That's why you can use a relative paths instead of absolute. Since Java 9, there was introduced a concept of modules. Moreover such illegal access issues became even stricter in the later versions. It's your own choice whether you want to break the conventions or not. But it's no longer a problem of the library if you don't follow the common rules. Do you agree with that?

**Comment by VigneshGuhan** [comment]
@sskorol  I agree with you. I was just sharing my experience which might help others who face similar issue.
Also can you add any custom exception in future release to address the above scenario

**Comment by sskorol** [comment]
@VigneshGuhan might be an option. Can you provide a link to a minimal example (GitHub repo) of how I can reproduce this issue? It'll help me a lot in handling such sort of exceptions. Thanks.

**Comment by sskorol** [comment]
@AmitBhaawsar ok, seems like I caught it. And it's very specific to Gradle and Java version.

For everyone else facing access issues on latest Gradle and JDK 17+, add the following to your build config:
```groovy
test {
    doFirst {
        jvmArgs(
            "-javaagent:${configurations.agent.singleFile}",
            '--add-opens', 'java.base/java.lang=ALL-UNNAMED'
        )
    }
    
    useTestNG()
}
```

**Comment by sskorol** [comment]
Docs are updated. Similar issue was described [here](https://github.com/sskorol/test-data-supplier/issues/119#issuecomment-1134499421). And fix was actually the same. Completely forgot about it.
