### ISSUE TITLE
[BUG] Different error occurs  when I used test-data- supplier 1.9.7 and with 2.2.0

### ISSUE THREAD

**Issue by Manish26g** [sskorol/test-data-supplier#192]
**Error for 1.9.7**
**Test Data Supplier version- 1.9.7
Java version - 11.0.16
Zero Cell-0.5.1**
And the respective code which i used below:

```
public class TestData {
    @Column(name="TestCase", index=0)
    public String TestCase;

    @Column(name="TestName", index=1)
    public String TestName;

    @Column(name="Execute", index=2)
    public String Execute;

    @Column(name="Email", index=3)
    public String Email;

    @Column(name="Password", index=4)
    public String Password;
```

```
public class dataSupplierUtils {   

    @DataSupplier
    public StreamEx<TestData> getData(){
        return TestDataReader.use(XlsxReader.class)
                .withTarget(TestData.class)
                .withSource("testdata.xlsx")
                .read()
                .filter(testdata -> testdata.Execute.equalsIgnoreCase("Yes"));

    }
```

Test:
  @Test(dataProvider = "getData",dataProviderClass = dataSupplierUtils.class)
    ```
public void testLogin(TestData testData){
        new HomePage01()
                .clickLogin(MenuType.MYACCOUNT, SubMenuType.LOGIN);
        new LoginPage()
                .loginToApplication(testData.Email,testData.Password);
    }
```
And after running the test via testng error displayed
org.joor.ReflectException: java.lang.reflect.InvocationTargetException
	at org.joor.Reflect.on(Reflect.java:914)
	at org.joor.Reflect.call(Reflect.java:575)
	at io.github.sskorol.utils.ReflectionUtils.invokeDataSupplier(ReflectionUtils.java:69)
	at io.github.sskorol.model.DataSupplierMetaData.obtainReturnValue(DataSupplierMetaData.java:54)
	at io.github.sskorol.model.DataSupplierMetaData.transform(DataSupplierMetaData.java:40)
	at io.github.sskorol.model.DataSupplierMetaData.&lt;init&gt;(DataSupplierMetaData.java:36)
	at io.github.sskorol.core.DataProviderTransformer.getMetaData(DataProviderTransformer.java:43)
	at io.github.sskorol.core.DataProviderTransformer.supplySeqData(DataProviderTransformer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.joor.Reflect.on(Reflect.java:910)
	... 35 more
Caused by: org.joor.ReflectException: java.lang.reflect.InvocationTargetException
	at org.joor.Reflect.on(Reflect.java:914)
	at org.joor.Reflect.call(Reflect.java:575)
	at org.joor.Reflect.call(Reflect.java:528)
	at io.github.sskorol.data.TestDataReader$DataBuilder.read(TestDataReader.java:54)
	at com.lambdaEcommerce.utils.dataSupplier.dataSupplierUtils.getData(dataSupplierUtils.java:27)--- after clicking this it navigates to the "read()"

**Error for 2.2.0**
**Test Data Supplier version- 2.2.0
Java version - 11.0.16
Zero Cell-0.5.1**

Using the code and with updated Test Data Supplier maven version and run the test it throws this kind of error

java: cannot access io.github.sskorol.core.DataSupplier
  bad class file: /C:/Users/Manish/.m2/repository/io/github/sskorol/test-data-supplier/2.2.0/test-data-supplier-2.2.0.jar!/io/github/sskorol/core/DataSupplier.class
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by Manish26g** [comment]
Sorry as i put the label as BUG which I myself dont know is it bug or issue, so closing this one but with the same i again reposting with no label
