### ISSUE TITLE
@DataSupplier doesn't work with @Factory

### ISSUE THREAD

**Issue by da-yaroslav-orel** [sskorol/test-data-supplier#48]
```
public class SimpleTest{

    int i;

    @DataSupplier
    public Object[] ints(){
        return new Object[] {1, 2, 3};
    }

    public SimpleTest(){}

    @Factory(dataProvider = "ints")
    public SimpleTest(int i){
    this.i = i;
    }

    @Test
    public void simpleTest() {
        System.out.println("Simple Test Method " + i);
    }
}
```

Output:
```
Method public SimpleTest(int) requires a @DataProvider named : ints
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:336)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:498)
	at org.testng.internal.FactoryMethod.invoke(FactoryMethod.java:71)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:158)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:40)
	at org.testng.TestRunner.initMethods(TestRunner.java:401)
	at org.testng.TestRunner.init(TestRunner.java:250)
	at org.testng.TestRunner.init(TestRunner.java:220)
	at org.testng.TestRunner.<init>(TestRunner.java:161)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:578)
	at org.testng.SuiteRunner.init(SuiteRunner.java:185)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:131)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1383)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1363)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1217)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

If we change @DataSupplier to @DataProvider everything works fine

**Comment by sskorol** [comment]
@da-yaroslav-orel that's true, factories are not supported at moment. I'm not using them on real projects at all, so haven't even thought about their coverage.

Are you using factories on a daily basis? Or it's just a note, like "would be nice to have"?

**Comment by da-yaroslav-orel** [comment]
Yeah. We use factories extensively. We need this feature. When do you think test-data-supplier would support it?

**Comment by sskorol** [comment]
@da-yaroslav-orel ok, got it, I'll estimate it tomorrow.

**Comment by sskorol** [comment]
@da-yaroslav-orel checked it. Currently `IAnnotationTransformer2` doesn't inject `dataProviderClass` into factory meta-data. So it makes impossible to determine data provider location for further invocation.

I've raised an issue on TestNG side. Maybe folks will suggest some other approaches could be used for factories interception, so that I could retrieve required `DataSupplier` meta-data.

**Comment by yaroslav-orel** [comment]
@sskorol got it. And what if we specify dataProviderClass explicitly? Would this work?

**Comment by sskorol** [comment]
@yaroslav-orel I'll check if it'd be easy to workaround it with an explicit dataProviderClass declaration.

**Comment by sskorol** [comment]
Will release a new version tomorrow.

**Comment by da-yaroslav-orel** [comment]
@sskorol sounds great. Thanks.

**Comment by sskorol** [comment]
@da-yaroslav-orel it's already in jcenter / maven central.

**Comment by da-yaroslav-orel** [comment]
@sskorol awesome. What a quick turnaround. Thanks

**Comment by sskorol** [comment]
@da-yaroslav-orel btw, new https://github.com/sskorol/test-data-supplier-plugin version is already on review in JetBrains. Should be approved within 2 days. After that, you'll be able to see IntelliJ inspections for `@Factory` as well.
